# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Aeos
                                 A QGIS plugin
 Plugin for LiDAR Simulator HELIOS++
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-18
        copyright            : (C) 2021 by Mark Searle
        email                : mark.searle@uni-heidelberg.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Aeos class from file Aeos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aeos import Aeos
    return Aeos(iface)
